name: jigar
on: 
  workflow-dispatch:
    branches:
      -main
jobs:
  sample_job:
    runs-on: ubuntu-latest

    steps:
      - name: print
        run: |
          echo hi
          echo hello
          echo hurray
