name: jigar
on: 
    workflow_dispatch:
        
jobs:
  sample_job:
    runs-on: ubuntu-latest

    steps:
      - name: print
        run: |
          echo hi
          echo hello
          echo `hostname`
